export const ERR_BAD_REQUEST = 'ERR_BAD_REQUEST';
export const ERR_NOT_FOUND = 'ERR_NOT_FOUND';
export const ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED';
export const ERR_FORBIDDEN = 'ERR_FORBIDDEN';
export const ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR';